import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'rw' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translations for all languages
const translations = {
  en: {
    // Common
    'common.search': 'Search',
    'common.cart': 'Cart',
    'common.wishlist': 'Wishlist',
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.logout': 'Logout',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.price': 'Price',
    'common.stock': 'Stock',
    'common.category': 'Category',
    'common.brand': 'Brand',
    'common.rating': 'Rating',
    'common.reviews': 'Reviews',
    'common.description': 'Description',
    'common.details': 'Details',
    'common.shipping': 'Shipping',
    'common.payment': 'Payment',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.discount': 'Discount',
    'common.free': 'Free',
    
    // Header
    'header.search_placeholder': 'Search for products...',
    'header.all_categories': 'All Categories',
    'header.become_seller': 'Become a Seller',
    'header.my_account': 'My Account',
    'header.orders': 'My Orders',
    'header.settings': 'Settings',
    'header.help': 'Help & Support',
    'header.language': 'Language',
    'header.currency': 'Currency',
    'header.online_expo': 'Online Expo',
    'header.my_shop': 'My Shop',
    'header.become_sponsor': 'Become Sponsor',
    'header.points': 'pts',
    
    // Auth
    'auth.welcome': 'Welcome to Bako',
    'auth.subtitle': 'The most powerful marketplace platform',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.full_name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot password?',
    'auth.sign_in': 'Sign In',
    'auth.create_account': 'Create Account',
    'auth.already_have_account': 'Already have an account?',
    'auth.dont_have_account': "Don't have an account?",
    'auth.or_continue_with': 'Or continue with',
    'auth.quick_login': 'Quick login with',
    
    // Products
    'products.add_to_cart': 'Add to Cart',
    'products.buy_now': 'Buy Now',
    'products.add_to_wishlist': 'Add to Wishlist',
    'products.compare': 'Compare',
    'products.quick_view': 'Quick View',
    'products.out_of_stock': 'Out of Stock',
    'products.in_stock': 'In Stock',
    'products.free_shipping': 'Free Shipping',
    'products.limited_stock': 'Limited Stock',
    'products.specifications': 'Specifications',
    'products.features': 'Features',
    'products.related_products': 'Related Products',
    'products.recommended': 'Recommended for You',
    'products.recently_viewed': 'Recently Viewed',
    'products.top_rated': 'Top Rated',
    'products.best_sellers': 'Best Sellers',
    'products.new_arrivals': 'New Arrivals',
    'products.flash_deals': 'Flash Deals',
    
    // Seller Dashboard
    'seller.dashboard': 'Dashboard',
    'seller.products': 'Products',
    'seller.orders': 'Orders',
    'seller.customers': 'Customers',
    'seller.analytics': 'Analytics',
    'seller.settings': 'Settings',
    'seller.messages': 'Messages',
    'seller.add_product': 'Add Product',
    'seller.edit_product': 'Edit Product',
    'seller.product_name': 'Product Name',
    'seller.product_description': 'Product Description',
    'seller.product_price': 'Product Price',
    'seller.product_stock': 'Stock Quantity',
    'seller.product_images': 'Product Images',
    'seller.product_videos': 'Product Videos',
    'seller.upload_images': 'Upload Images',
    'seller.upload_videos': 'Upload Videos',
    'seller.total_revenue': 'Total Revenue',
    'seller.total_sales': 'Total Sales',
    'seller.total_products': 'Total Products',
    'seller.average_rating': 'Average Rating',
    'seller.shop_settings': 'Shop Settings',
    'seller.shop_name': 'Shop Name',
    'seller.shop_description': 'Shop Description',
    'seller.shop_logo': 'Shop Logo',
    'seller.shop_banner': 'Shop Banner',
    
    // Categories
    'category.electronics': 'Electronics & Gadgets',
    'category.fashion': 'Fashion & Apparel',
    'category.home': 'Home & Garden',
    'category.beauty': 'Beauty & Personal Care',
    'category.sports': 'Sports & Outdoors',
    'category.toys': 'Toys & Games',
    'category.books': 'Books & Media',
    'category.automotive': 'Automotive',
    'category.food': 'Food & Beverages',
    'category.health': 'Health & Wellness',
    'category.pets': 'Pet Supplies',
    'category.office': 'Office Supplies',
    'category.jewelry': 'Jewelry & Accessories',
    'category.arts': 'Arts & Crafts',
    'category.baby': 'Baby & Kids',
    'category.services': 'Services',
    
    // Messages
    'message.added_to_cart': 'Product added to cart!',
    'message.added_to_wishlist': 'Added to wishlist!',
    'message.removed_from_wishlist': 'Removed from wishlist!',
    'message.login_required': 'Please login to continue',
    'message.error_occurred': 'An error occurred',
    'message.success': 'Success!',
    'message.product_deleted': 'Product deleted successfully',
    'message.changes_saved': 'Changes saved successfully',
  },
  
  fr: {
    // Common
    'common.search': 'Rechercher',
    'common.cart': 'Panier',
    'common.wishlist': 'Liste de souhaits',
    'common.login': 'Connexion',
    'common.signup': "S'inscrire",
    'common.logout': 'Déconnexion',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.close': 'Fermer',
    'common.loading': 'Chargement...',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.all': 'Tout',
    'common.price': 'Prix',
    'common.stock': 'Stock',
    'common.category': 'Catégorie',
    'common.brand': 'Marque',
    'common.rating': 'Évaluation',
    'common.reviews': 'Avis',
    'common.description': 'Description',
    'common.details': 'Détails',
    'common.shipping': 'Livraison',
    'common.payment': 'Paiement',
    'common.total': 'Total',
    'common.subtotal': 'Sous-total',
    'common.discount': 'Réduction',
    'common.free': 'Gratuit',
    
    // Header
    'header.search_placeholder': 'Rechercher des produits...',
    'header.all_categories': 'Toutes les catégories',
    'header.become_seller': 'Devenir vendeur',
    'header.my_account': 'Mon compte',
    'header.orders': 'Mes commandes',
    'header.settings': 'Paramètres',
    'header.help': 'Aide et support',
    'header.language': 'Langue',
    'header.currency': 'Devise',
    'header.online_expo': 'Expo en ligne',
    'header.my_shop': 'Ma boutique',
    'header.become_sponsor': 'Devenir sponsor',
    'header.points': 'pts',
    
    // Auth
    'auth.welcome': 'Bienvenue sur Bako',
    'auth.subtitle': 'La plateforme de marché la plus puissante',
    'auth.email': 'Adresse e-mail',
    'auth.password': 'Mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.full_name': 'Nom complet',
    'auth.phone': 'Numéro de téléphone',
    'auth.remember_me': 'Se souvenir de moi',
    'auth.forgot_password': 'Mot de passe oublié?',
    'auth.sign_in': 'Se connecter',
    'auth.create_account': 'Créer un compte',
    'auth.already_have_account': 'Vous avez déjà un compte?',
    'auth.dont_have_account': "Vous n'avez pas de compte?",
    'auth.or_continue_with': 'Ou continuer avec',
    'auth.quick_login': 'Connexion rapide avec',
    
    // Products
    'products.add_to_cart': 'Ajouter au panier',
    'products.buy_now': 'Acheter maintenant',
    'products.add_to_wishlist': 'Ajouter aux favoris',
    'products.compare': 'Comparer',
    'products.quick_view': 'Aperçu rapide',
    'products.out_of_stock': 'Rupture de stock',
    'products.in_stock': 'En stock',
    'products.free_shipping': 'Livraison gratuite',
    'products.limited_stock': 'Stock limité',
    'products.specifications': 'Spécifications',
    'products.features': 'Caractéristiques',
    'products.related_products': 'Produits connexes',
    'products.recommended': 'Recommandé pour vous',
    'products.recently_viewed': 'Vus récemment',
    'products.top_rated': 'Les mieux notés',
    'products.best_sellers': 'Meilleures ventes',
    'products.new_arrivals': 'Nouveautés',
    'products.flash_deals': 'Offres flash',
    
    // Seller Dashboard
    'seller.dashboard': 'Tableau de bord',
    'seller.products': 'Produits',
    'seller.orders': 'Commandes',
    'seller.customers': 'Clients',
    'seller.analytics': 'Analytique',
    'seller.settings': 'Paramètres',
    'seller.messages': 'Messages',
    'seller.add_product': 'Ajouter un produit',
    'seller.edit_product': 'Modifier le produit',
    'seller.product_name': 'Nom du produit',
    'seller.product_description': 'Description du produit',
    'seller.product_price': 'Prix du produit',
    'seller.product_stock': 'Quantité en stock',
    'seller.product_images': 'Images du produit',
    'seller.product_videos': 'Vidéos du produit',
    'seller.upload_images': 'Télécharger des images',
    'seller.upload_videos': 'Télécharger des vidéos',
    'seller.total_revenue': 'Revenu total',
    'seller.total_sales': 'Ventes totales',
    'seller.total_products': 'Produits totaux',
    'seller.average_rating': 'Note moyenne',
    'seller.shop_settings': 'Paramètres de la boutique',
    'seller.shop_name': 'Nom de la boutique',
    'seller.shop_description': 'Description de la boutique',
    'seller.shop_logo': 'Logo de la boutique',
    'seller.shop_banner': 'Bannière de la boutique',
    
    // Categories
    'category.electronics': 'Électronique & Gadgets',
    'category.fashion': 'Mode & Vêtements',
    'category.home': 'Maison & Jardin',
    'category.beauty': 'Beauté & Soins personnels',
    'category.sports': 'Sports & Plein air',
    'category.toys': 'Jouets & Jeux',
    'category.books': 'Livres & Médias',
    'category.automotive': 'Automobile',
    'category.food': 'Alimentation & Boissons',
    'category.health': 'Santé & Bien-être',
    'category.pets': 'Animaux de compagnie',
    'category.office': 'Fournitures de bureau',
    'category.jewelry': 'Bijoux & Accessoires',
    'category.arts': 'Arts & Artisanat',
    'category.baby': 'Bébé & Enfants',
    'category.services': 'Services',
    
    // Messages
    'message.added_to_cart': 'Produit ajouté au panier!',
    'message.added_to_wishlist': 'Ajouté aux favoris!',
    'message.removed_from_wishlist': 'Retiré des favoris!',
    'message.login_required': 'Veuillez vous connecter pour continuer',
    'message.error_occurred': 'Une erreur est survenue',
    'message.success': 'Succès!',
    'message.product_deleted': 'Produit supprimé avec succès',
    'message.changes_saved': 'Modifications enregistrées avec succès',
  },
  
  rw: {
    // Common (Kinyarwanda)
    'common.search': 'Shakisha',
    'common.cart': 'Igitebo',
    'common.wishlist': 'Ibyifuzo',
    'common.login': 'Injira',
    'common.signup': 'Iyandikishe',
    'common.logout': 'Sohoka',
    'common.save': 'Bika',
    'common.cancel': 'Hagarika',
    'common.delete': 'Siba',
    'common.edit': 'Hindura',
    'common.view': 'Reba',
    'common.add': 'Ongeraho',
    'common.remove': 'Kuraho',
    'common.close': 'Funga',
    'common.loading': 'Gupakira...',
    'common.yes': 'Yego',
    'common.no': 'Oya',
    'common.all': 'Byose',
    'common.price': 'Igiciro',
    'common.stock': 'Ububiko',
    'common.category': 'Icyiciro',
    'common.brand': 'Ikirango',
    'common.rating': 'Amanota',
    'common.reviews': 'Ibitekerezo',
    'common.description': 'Ibisobanuro',
    'common.details': 'Amakuru',
    'common.shipping': 'Kohereza',
    'common.payment': 'Kwishyura',
    'common.total': 'Igiteranyo',
    'common.subtotal': 'Igice cyose',
    'common.discount': 'Igabanuka',
    'common.free': 'Kugura',
    
    // Header
    'header.search_placeholder': 'Shakisha ibicuruzwa...',
    'header.all_categories': 'Ibyiciro byose',
    'header.become_seller': 'Ba umucuruzi',
    'header.my_account': 'Konti yanjye',
    'header.orders': 'Ibyo naguze',
    'header.settings': 'Igenamiterere',
    'header.help': 'Ubufasha',
    'header.language': 'Ururimi',
    'header.currency': 'Ifaranga',
    'header.online_expo': 'Expo en ligne',
    'header.my_shop': 'Aduka yanjye',
    'header.become_sponsor': 'Ba umusponsor',
    'header.points': 'pts',
    
    // Auth
    'auth.welcome': 'Murakaza neza kuri Bako',
    'auth.subtitle': 'Urubuga rukomeye rwo gucuruza',
    'auth.email': 'Aderesi ya imeri',
    'auth.password': 'Ijambo ryibanga',
    'auth.confirm_password': 'Emeza ijambo ryibanga',
    'auth.full_name': 'Amazina yose',
    'auth.phone': 'Nimero ya telefoni',
    'auth.remember_me': 'Nyibuka',
    'auth.forgot_password': 'Wibagiwe ijambo ryibanga?',
    'auth.sign_in': 'Injira',
    'auth.create_account': 'Fungura konti',
    'auth.already_have_account': 'Ufite konti?',
    'auth.dont_have_account': 'Nta konti ufite?',
    'auth.or_continue_with': 'Cyangwa komeza na',
    'auth.quick_login': 'Kwinjira vuba na',
    
    // Products
    'products.add_to_cart': 'Shyira mugikorwa',
    'products.buy_now': 'Gura nonaha',
    'products.add_to_wishlist': 'Ongeraho ibyifuzo',
    'products.compare': 'Gereranya',
    'products.quick_view': 'Reba vuba',
    'products.out_of_stock': 'Nta bubiko',
    'products.in_stock': 'Bubiko',
    'products.free_shipping': 'Kohereza kubusa',
    'products.limited_stock': 'Ububiko buke',
    'products.specifications': 'Ibisobanuro',
    'products.features': 'Ibiranga',
    'products.related_products': 'Ibicuruzwa bifitanye',
    'products.recommended': 'Byasabwe kuri wewe',
    'products.recently_viewed': 'Byarebwe vuba aha',
    'products.top_rated': 'Bikunzwe cyane',
    'products.best_sellers': 'Ibyo bigurwa cyane',
    'products.new_arrivals': 'Bishya',
    'products.flash_deals': 'Amakuru yihuse',
    
    // Seller Dashboard
    'seller.dashboard': 'Ikibanza',
    'seller.products': 'Ibicuruzwa',
    'seller.orders': 'Ibisabwa',
    'seller.customers': 'Abakiriya',
    'seller.analytics': 'Isesengura',
    'seller.settings': 'Igenamiterere',
    'seller.messages': 'Ubutumwa',
    'seller.add_product': 'Ongeraho igicuruzwa',
    'seller.edit_product': 'Hindura igicuruzwa',
    'seller.product_name': "Izina ry'igicuruzwa",
    'seller.product_description': "Ibisobanuro by'igicuruzwa",
    'seller.product_price': "Igiciro cy'igicuruzwa",
    'seller.product_stock': 'Umubare mububiko',
    'seller.product_images': 'Amafoto yigicuruzwa',
    'seller.product_videos': 'Amavideo yigicuruzwa',
    'seller.upload_images': 'Ohereza amafoto',
    'seller.upload_videos': 'Ohereza amavideo',
    'seller.total_revenue': 'Amafaranga yose',
    'seller.total_sales': 'Igurisha ryose',
    'seller.total_products': 'Ibicuruzwa byose',
    'seller.average_rating': 'Amanota yo hagati',
    'seller.shop_settings': 'Igenamiterere ryaduka',
    'seller.shop_name': 'Izina ryaduka',
    'seller.shop_description': 'Ibisobanuro byaduka',
    'seller.shop_logo': 'Ikirango cyaduka',
    'seller.shop_banner': 'Icapa cyaduka',
    
    // Categories
    'category.electronics': 'Ikoranabuhanga',
    'category.fashion': 'Imyambarire',
    'category.home': 'Inzu & Ubusitani',
    'category.beauty': 'Ubwiza & Kwita kumubiri',
    'category.sports': 'Siporo & Hanze',
    'category.toys': 'Ibikinisho & Imikino',
    'category.books': 'Ibitabo & Itangazamakuru',
    'category.automotive': 'Imodoka',
    'category.food': 'Ibiryo & Ibinyobwa',
    'category.health': 'Ubuzima',
    'category.pets': 'Inyamaswa zororwa',
    'category.office': 'Ibikoresho byabiro',
    'category.jewelry': 'Imitako & Ibikoresho',
    'category.arts': 'Ubuhanzi',
    'category.baby': 'Abana bato',
    'category.services': 'Serivisi',
    
    // Messages
    'message.added_to_cart': 'Igicuruzwa cyashyizwe mugikorwa!',
    'message.added_to_wishlist': 'Byashyizwe mubyifuzo!',
    'message.removed_from_wishlist': 'Byakuweho mubyifuzo!',
    'message.login_required': 'Injira kugirango ukomeze',
    'message.error_occurred': 'Habayeho ikosa',
    'message.success': 'Byagenze neza!',
    'message.product_deleted': 'Igicuruzwa cyasibwe neza',
    'message.changes_saved': 'Impinduka zabitswe neza',
  },
  
  sw: {
    // Common (Swahili)
    'common.search': 'Tafuta',
    'common.cart': 'Kikopo',
    'common.wishlist': 'Orodha ya matakwa',
    'common.login': 'Ingia',
    'common.signup': 'Jisajili',
    'common.logout': 'Toka',
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.delete': 'Futa',
    'common.edit': 'Hariri',
    'common.view': 'Tazama',
    'common.add': 'Ongeza',
    'common.remove': 'Ondoa',
    'common.close': 'Funga',
    'common.loading': 'Inapakia...',
    'common.yes': 'Ndiyo',
    'common.no': 'Hapana',
    'common.all': 'Yote',
    'common.price': 'Bei',
    'common.stock': 'Hisa',
    'common.category': 'Jamii',
    'common.brand': 'Chapa',
    'common.rating': 'Ukadiriaji',
    'common.reviews': 'Maoni',
    'common.description': 'Maelezo',
    'common.details': 'Maelezo',
    'common.shipping': 'Usafirishaji',
    'common.payment': 'Malipo',
    'common.total': 'Jumla',
    'common.subtotal': 'Jumla ndogo',
    'common.discount': 'Punguzo',
    'common.free': 'Bure',
    
    // Header
    'header.search_placeholder': 'Tafuta bidhaa...',
    'header.all_categories': 'Makundi yote',
    'header.become_seller': 'Kuwa muuzaji',
    'header.my_account': 'Akaunti yangu',
    'header.orders': 'Maagizo yangu',
    'header.settings': 'Mipangilio',
    'header.help': 'Msaada',
    'header.language': 'Lugha',
    'header.currency': 'Sarafu',
    'header.online_expo': 'Expo en line',
    'header.my_shop': 'Duka yangu',
    'header.become_sponsor': 'Kuwa mshirika',
    'header.points': 'pts',
    
    // Auth
    'auth.welcome': 'Karibu Bako',
    'auth.subtitle': 'Jukwaa la soko lenye nguvu zaidi',
    'auth.email': 'Barua pepe',
    'auth.password': 'Nenosiri',
    'auth.confirm_password': 'Thibitisha nenosiri',
    'auth.full_name': 'Jina kamili',
    'auth.phone': 'Namba ya simu',
    'auth.remember_me': 'Nikumbuke',
    'auth.forgot_password': 'Umesahau nenosiri?',
    'auth.sign_in': 'Ingia',
    'auth.create_account': 'Fungua akaunti',
    'auth.already_have_account': 'Una akaunti tayari?',
    'auth.dont_have_account': 'Huna akaunti?',
    'auth.or_continue_with': 'Au endelea na',
    'auth.quick_login': 'Ingia haraka na',
    
    // Products
    'products.add_to_cart': 'Ongeza kwenye kikopo',
    'products.buy_now': 'Nunua sasa',
    'products.add_to_wishlist': 'Ongeza kwenye matakwa',
    'products.compare': 'Linganisha',
    'products.quick_view': 'Angalia haraka',
    'products.out_of_stock': 'Haipo',
    'products.in_stock': 'Ipo',
    'products.free_shipping': 'Usafirishaji bure',
    'products.limited_stock': 'Hisa ndogo',
    'products.specifications': 'Vipengele',
    'products.features': 'Vipengele',
    'products.related_products': 'Bidhaa zinazofanana',
    'products.recommended': 'Inapendekezwa kwako',
    'products.recently_viewed': 'Ulizotazama hivi karibuni',
    'products.top_rated': 'Zilizo bora',
    'products.best_sellers': 'Zinazouzwa zaidi',
    'products.new_arrivals': 'Mpya',
    'products.flash_deals': 'Ofa za haraka',
    
    // Seller Dashboard
    'seller.dashboard': 'Dashibodi',
    'seller.products': 'Bidhaa',
    'seller.orders': 'Maagizo',
    'seller.customers': 'Wateja',
    'seller.analytics': 'Uchambuzi',
    'seller.settings': 'Mipangilio',
    'seller.messages': 'Ujumbe',
    'seller.add_product': 'Ongeza bidhaa',
    'seller.edit_product': 'Hariri bidhaa',
    'seller.product_name': 'Jina la bidhaa',
    'seller.product_description': 'Maelezo ya bidhaa',
    'seller.product_price': 'Bei ya bidhaa',
    'seller.product_stock': 'Wingi wa hisa',
    'seller.product_images': 'Picha za bidhaa',
    'seller.product_videos': 'Video za bidhaa',
    'seller.upload_images': 'Pakia picha',
    'seller.upload_videos': 'Pakia video',
    'seller.total_revenue': 'Mapato yote',
    'seller.total_sales': 'Mauzo yote',
    'seller.total_products': 'Bidhaa zote',
    'seller.average_rating': 'Wastani wa ukadiriaji',
    'seller.shop_settings': 'Mipangilio ya duka',
    'seller.shop_name': 'Jina la duka',
    'seller.shop_description': 'Maelezo ya duka',
    'seller.shop_logo': 'Nembo ya duka',
    'seller.shop_banner': 'Bango la duka',
    
    // Categories
    'category.electronics': 'Elektroniki',
    'category.fashion': 'Mitindo',
    'category.home': 'Nyumba & Bustani',
    'category.beauty': 'Uzuri',
    'category.sports': 'Michezo',
    'category.toys': 'Vitu vya kuchezea',
    'category.books': 'Vitabu',
    'category.automotive': 'Magari',
    'category.food': 'Chakula',
    'category.health': 'Afya',
    'category.pets': 'Wanyama wa kufugwa',
    'category.office': 'Ofisi',
    'category.jewelry': 'Vito',
    'category.arts': 'Sanaa',
    'category.baby': 'Watoto wachanga',
    'category.services': 'Huduma',
    
    // Messages
    'message.added_to_cart': 'Bidhaa imeongezwa kwenye kikopo!',
    'message.added_to_wishlist': 'Imeongezwa kwenye matakwa!',
    'message.removed_from_wishlist': 'Imeondolewa kutoka matakwa!',
    'message.login_required': 'Tafadhali ingia ili kuendelea',
    'message.error_occurred': 'Kosa limetokea',
    'message.success': 'Imefanikiwa!',
    'message.product_deleted': 'Bidhaa imefutwa',
    'message.changes_saved': 'Mabadiliko yamehifadhiwa',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('bako_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('bako_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}